var GRAVES_DATA = {
  symbols: {
    "crow": {
      img: "crow.png",
      x: 30,
      y: -13,
    },
    "hand": {
      img: "zombie_hand_small.png",
      x: 19,
      y: 82,
    }
  },
  sign: "graveyard_sign.jpg",
  graves: [
    {
      name: "Daenerys Targaryen",
      sub: "Died Ep. 73",
      url: "https://gameofthrones.fandom.com/wiki/Daenerys_Targaryen",
      style: "fresh",
      img: "Targaryen.jpg",
      symbols: [],
      id: 129,
    },
    {
      name: "Cersei Lannister",
      sub: "Died Ep. 72",
      url: "https://en.wikipedia.org/wiki/Cersei_Lannister",
      style: "",
      img: "Lannister.jpg",
      symbols: [],
      id: 128,
    },
    {
      name: "Jaime Lannister",
      sub: "Died Ep. 72",
      url: "https://en.wikipedia.org/wiki/Jaime_Lannister",
      style: "",
      img: "Lannister.jpg",
      symbols: [],
      id: 127,
    },
    {
      name: "Sandor Clegane",
      sub: "Died Ep. 72",
      url: "https://en.wikipedia.org/wiki/Sandor_Clegane",
      style: "",
      img: "",
      symbols: [],
      id: 126,
    },
    {
      name: "Gregor Clegane",
      sub: "Died Ep. 72",
      url: "https://gameofthrones.fandom.com/wiki/Gregor_Clegane",
      style: "",
      img: "",
      symbols: [],
      id: 125,
    },
    {
      name: "Qyburn",
      sub: "Died Ep. 72",
      url: "https://gameofthrones.fandom.com/wiki/Qyburn",
      style: "",
      img: "",
      symbols: [],
      id: 124,
    },
    {
      name: "Euron Greyjoy",
      sub: "Died Ep. 72",
      url: "https://gameofthrones.fandom.com/wiki/Euron_Greyjoy",
      style: "",
      img: "Greyjoy.jpg",
      symbols: [],
      id: 123,
    },
    {
      name: "Varys",
      sub: "Died Ep. 72",
      url: "https://gameofthrones.fandom.com/wiki/Varys",
      style: "",
      img: "",
      symbols: [],
      id: 122,
    },
    {
      name: "Missandei",
      sub: "Died Ep. 71",
      url: "https://gameofthrones.fandom.com/wiki/Missandei",
      style: "",
      img: "",
      symbols: [],
      id: 121,
    },
    {
      name: "Rhaegal",
      sub: "Died Ep. 71",
      url: "https://gameofthrones.fandom.com/wiki/Rhaegal",
      style: "",
      img: "",
      symbols: [],
      id: 120,
    },
    {
      name: "The Night King",
      sub: "Died Ep. 70",
      url: "https://gameofthrones.fandom.com/wiki/Night%27s_King",
      style: "",
      img: "",
      symbols: [],
      id: 119,
    },
    {
      name: "Melisandre",
      sub: "Died Ep. 70",
      url: "https://gameofthrones.fandom.com/wiki/Melisandre",
      style: "",
      img: "",
      symbols: [],
      id: 118,
    },
    {
      name: "Theon Greyjoy",
      sub: "Died Ep 70",
      url: "https://gameofthrones.fandom.com/wiki/Theon_Greyjoy",
      style: "",
      img: "Greyjoy.jpg",
      symbols: [],
      id: 117,
    },
    {
      name: "Jorah Mormont",
      sub: "Died Ep. 70",
      url: "https://gameofthrones.fandom.com/wiki/Jorah_Mormont",
      style: "",
      img: "",
      symbols: [],
      id: 116,
    },
    {
      name: "Lyanna Mormont",
      sub: "Died Ep. 70",
      url: "https://gameofthrones.fandom.com/wiki/Lyanna_Mormont",
      style: "",
      img: "",
      symbols: [],
      id: 115,
    },
    {
      name: "Berric Dondarrion",
      sub: "Died Ep. 70",
      url: "https://gameofthrones.fandom.com/wiki/Beric_Dondarrion",
      style: "",
      img: "",
      symbols: [],
      id: 114,
    },
    {
      name: "Eddison Tollett",
      sub: "Died Ep. 70",
      url: "https://gameofthrones.fandom.com/wiki/Eddison_Tollett",
      style: "",
      img: "",
      symbols: ["crow"],
      id: 113,
    },
    {
      name: "Ned Umber",
      sub: "Died Ep. 68",
      url: "https://gameofthrones.fandom.com/wiki/Ned_Umber",
      style: "",
      img: "",
      symbols: [],
      id: 112,
    },
    {
      name: "Petyr Baelish",
      sub: "Died Ep. 67",
      url: "http://gameofthrones.wikia.com/wiki/Petyr_Baelish",
      style: "",
      img: "",
      symbols: [],
      id: 111,
    },
    {
      name: "Thoros of Myr",
      sub: "Died Ep. 66",
      url: "http://gameofthrones.wikia.com/wiki/Thoros",
      style: "",
      img: "",
      symbols: [],
      id: 110,
    },
    {
      name: "Viserion",
      sub: "Died Ep. 66",
      url: "http://gameofthrones.wikia.com/wiki/Viserion",
      style: "",
      img: "Targaryen.jpg",
      symbols: [],
      id: 109,
    },
    {
      name: "Dickon Tarly",
      sub: "Died Ep. 65",
      url: "http://gameofthrones.wikia.com/wiki/Dickon_Tarly",
      style: "",
      img: "Tarly.jpg",
      symbols: [],
      id: 108,
    },
    {
      name: "Randyll Tarly",
      sub: "Died Ep. 65",
      url: "http://gameofthrones.wikia.com/wiki/Randyll_Tarly",
      style: "",
      img: "Tarly.jpg",
      symbols: [],
      id: 107,
    },
    {
      name: "Olenna Tyrell",
      sub: "Died Ep. 63",
      url: "http://gameofthrones.wikia.com/wiki/Olenna_Tyrell",
      style: "",
      img: "Tyrell.jpg",
      symbols: [],
      id: 106,
    },
    {
      name: "Tyene Sand",
      sub: "Died Ep. 63",
      url: "http://gameofthrones.wikia.com/wiki/Tyene_Sand",
      style: "",
      img: "Martell.jpg",
      symbols: [],
      id: 105,
    },
    {
      name: "Nymeria Sand",
      sub: "Died Ep. 62",
      url: "http://gameofthrones.wikia.com/wiki/Nymeria_Sand",
      style: "",
      img: "Martell.jpg",
      symbols: [],
      id: 104,
    },
    {
      name: "Obara Sand",
      sub: "Died Ep. 62",
      url: "http://gameofthrones.wikia.com/wiki/Obara_Sand",
      style: "",
      img: "Martell.jpg",
      symbols: [],
      id: 103,
    },
    {
      name: "Walder Frey",
      sub: "Died Ep. 60",
      url: "http://gameofthrones.wikia.com/wiki/Walder_Frey",
      style: "",
      img: "",
      symbols: [],
      id: 102,
    },
    {
      name: "Lothar Frey",
      sub: "Died Ep. 60",
      url: "http://gameofthrones.wikia.com/wiki/Lothar_Frey",
      style: "",
      img: "",
      symbols: [],
      id: 101,
    },
    {
      name: "Black Walder",
      sub: "Died Ep. 60",
      url: "http://gameofthrones.wikia.com/wiki/Walder_Rivers",
      style: "",
      img: "",
      symbols: [],
      id: 100,
    },
    {
      name: "Tommen Baratheon",
      sub: "Died Ep. 60",
      url: "http://gameofthrones.wikia.com/wiki/Tommen_Baratheon",
      style: "",
      img: "Baratheon.jpg",
      symbols: [],
      id: 99,
    },
    {
      name: "Kevan Lannister",
      sub: "Died Ep. 60",
      url: "http://gameofthrones.wikia.com/wiki/Kevan_Lannister",
      style: "",
      img: "Lannister.jpg",
      symbols: [],
      id: 98,
    },
    {
      name: "The High Sparrow",
      sub: "Died Ep. 60",
      url: "http://gameofthrones.wikia.com/wiki/High_Sparrow",
      style: "",
      img: "",
      symbols: [],
      id: 96,
    },
    {
      name: "Loras Tyrell",
      sub: "Died Ep. 60",
      url: "http://gameofthrones.wikia.com/wiki/Loras_Tyrell",
      style: "",
      img: "Tyrell.jpg",
      symbols: [],
      id: 95,
    },
    {
      name: "Mace Tyrell",
      sub: "Died Ep. 60",
      url: "http://gameofthrones.wikia.com/wiki/Mace_Tyrell",
      style: "",
      img: "Tyrell.jpg",
      symbols: [],
      id: 94,
    },
    {
      name: "Margaery Tyrell",
      sub: "Died Ep. 60",
      url: "http://gameofthrones.wikia.com/wiki/Margaery_Tyrell",
      style: "",
      img: "Tyrell.jpg",
      symbols: [],
      id: 93,
    },
    {
      name: "Lancel Lannister",
      sub: "Died Ep. 60",
      url: "http://gameofthrones.wikia.com/wiki/Lancel",
      style: "",
      img: "Lannister.jpg",
      symbols: [],
      id: 97,
    },
    {
      name: "Grand Maester Pycelle",
      sub: "Died Ep. 60",
      url: "http://gameofthrones.wikia.com/wiki/Pycelle",
      style: "",
      img: "",
      symbols: [],
      id: 92,
    },
    {
      name: "Ramsay Bolton",
      sub: "Died Ep. 59",
      url: "http://gameofthrones.wikia.com/wiki/Ramsay_Bolton",
      style: "",
      img: "",
      symbols: [],
      id: 89,
    },
    {
      name: "Wun Wun",
      sub: "Died Ep. 59",
      url: "http://gameofthrones.wikia.com/wiki/Wun_Weg_Wun_Dar_Wun",
      style: "",
      img: "",
      symbols: [],
      id: 88,
    },
    {
      name: "Jon Umber",
      sub: "Died Ep. 59",
      url: "http://gameofthrones.wikia.com/wiki/Smalljon_Umber",
      style: "",
      img: "",
      symbols: [],
      id: 87,
    },
    {
      name: "Rickon Stark",
      sub: "Died Ep. 59",
      url: "http://gameofthrones.wikia.com/wiki/Rickon_Stark",
      style: "",
      img: "Stark.jpg",
      symbols: [],
      id: 86,
    },
    {
      name: "Razdal mo Eraz",
      sub: "Died Ep. 59",
      url: "http://gameofthrones.wikia.com/wiki/Razdal_mo_Eraz",
      style: "",
      img: "",
      symbols: [],
      id: 90,
    },
    {
      name: "Belicho Paenymion",
      sub: "Died Ep. 59",
      url: "http://gameofthrones.wikia.com/wiki/Belicho_Paenymion",
      style: "",
      img: "",
      symbols: [],
      id: 91,
    },
    {
      name: "Lady Crane",
      sub: "Died Ep. 58",
      url: "http://gameofthrones.wikia.com/wiki/Lady_Crane",
      style: "",
      img: "",
      symbols: [],
      id: 85,
    },
    {
      name: "Lem Lemoncloak",
      sub: "Died Ep. 58",
      url: "http://gameofthrones.wikia.com/wiki/Lem",
      style: "",
      img: "",
      symbols: [],
      id: 84,
    },
    {
      name: "The Waif",
      sub: "Died Ep. 58",
      url: "http://gameofthrones.wikia.com/wiki/Waif",
      style: "",
      img: "",
      symbols: [],
      id: 83,
    },
    {
      name: "The Blackfish",
      sub: "Died Ep. 58",
      url: "http://gameofthrones.wikia.com/wiki/Brynden_Tully",
      style: "",
      img: "Tully.jpg",
      symbols: [],
      id: 82,
    },
    {
      name: "Hodor",
      sub: "Died Ep. 55",
      url: "http://gameofthrones.wikia.com/wiki/Summer",
      style: "",
      img: "",
      symbols: [],
      id: 79,
    },
    {
      name: "Leaf",
      sub: "Died Ep. 55",
      url: "http://gameofthrones.wikia.com/wiki/Leaf",
      style: "",
      img: "",
      symbols: [],
      id: 80,
    },
    {
      name: "Three-eyed raven",
      sub: "Died Ep. 55",
      url: "http://gameofthrones.wikia.com/wiki/Three-eyed_raven",
      style: "",
      img: "",
      symbols: [],
      id: 81,
    },
    {
      name: "Summer",
      sub: "Died Ep. 55",
      url: "http://gameofthrones.wikia.com/wiki/Summer",
      style: "",
      img: "Stark.jpg",
      symbols: [],
      id: 78,
    },
    {
      name: "Osha",
      sub: "Died Ep. 54",
      url: "http://gameofthrones.wikia.com/wiki/Osha",
      style: "",
      img: "",
      symbols: [],
      id: 77,
    },
    {
      name: "Shaggydog",
      sub: "Died Ep. 53",
      url: "http://gameofthrones.wikia.com/wiki/Shaggydog",
      style: "",
      img: "Stark.jpg",
      symbols: [],
      id: 76,
    },
    {
      name: "Olly",
      sub: "Died Ep. 53",
      url: "http://gameofthrones.wikia.com/wiki/Olly",
      style: "",
      img: "",
      symbols: ["crow"],
      id: 74,
    },
    {
      name: "Alliser Thorne",
      sub: "Died Ep. 53",
      url: "http://gameofthrones.wikia.com/wiki/Alliser_Thorne",
      style: "",
      img: "",
      symbols: ["crow"],
      id: 73,
    },
    {
      name: "Balon Greyjoy",
      sub: "Died Ep. 52",
      url: "http://gameofthrones.wikia.com/wiki/Balon_Greyjoy",
      style: "",
      img: "Greyjoy.jpg",
      symbols: [],
      id: 72,
    },
    {
      name: "Walda Frey",
      sub: "Died Ep. 52",
      url: "http://gameofthrones.wikia.com/wiki/Walda_Bolton",
      style: "",
      img: "",
      symbols: [],
      id: 75,
    },
    {
      name: "Roose Bolton",
      sub: "Died Ep. 52",
      url: "http://gameofthrones.wikia.com/wiki/Roose_Bolton",
      style: "",
      img: "",
      symbols: [],
      id: 71,
    },
    {
      name: "Doran Martell",
      sub: "Died Ep. 51",
      url: "http://gameofthrones.wikia.com/wiki/Doran_Martell",
      style: "",
      img: "Martell.jpg",
      symbols: [],
      id: 69,
    },
    {
      name: "Trystane Martell",
      sub: "Died Ep. 51",
      url: "http://gameofthrones.wikia.com/wiki/Trystane_Martell",
      style: "",
      img: "Martell.jpg",
      symbols: [],
      id: 68,
    },
    {
      name: "Areo Hotah",
      sub: "Died Ep. 51",
      url: "http://gameofthrones.wikia.com/wiki/Areo_Hotah",
      style: "",
      img: "",
      symbols: [],
      id: 70,
    },
    {
      name: "Jon Snow",
      sub: "Died Ep. 50",
      url: "http://gameofthrones.wikia.com/wiki/Jon_Snow",
      style: "",
      img: "Stark.jpg",
      symbols: ["hand"],
      id: 64,
    },
    {
      name: "Myrcella Baratheon",
      sub: "Died Ep. 50",
      url: "http://gameofthrones.wikia.com/wiki/Myrcella_Baratheon",
      style: "",
      img: "Baratheon.jpg",
      symbols: [],
      id: 63,
    },
    {
      name: "Meryn Trant",
      sub: "Died Ep. 50",
      url: "http://gameofthrones.wikia.com/wiki/Meryn_Trant",
      style: "",
      img: "",
      symbols: [],
      id: 62,
    },
    {
      name: "Myranda",
      sub: "Died Ep. 50",
      url: "http://gameofthrones.wikia.com/wiki/Myranda",
      style: "",
      img: "",
      symbols: [],
      id: 61,
    },
    {
      name: "Stannis Baratheon",
      sub: "Died Ep. 50",
      url: "http://gameofthrones.wikia.com/wiki/Stannis_Baratheon",
      style: "",
      img: "Baratheon.jpg",
      symbols: [],
      id: 60,
    },
    {
      name: "Selyse Baratheon",
      sub: "Died Ep. 50",
      url: "http://gameofthrones.wikia.com/wiki/Selyse_Baratheon",
      style: "",
      img: "Baratheon.jpg",
      symbols: [],
      id: 59,
    },
    {
      name: "Hizdahr zo Loraq",
      sub: "Died Ep. 49",
      url: "http://gameofthrones.wikia.com/wiki/Hizdahr_zo_Loraq",
      style: "",
      img: "",
      symbols: [],
      id: 65,
    },
    {
      name: "Shireen Baratheon",
      sub: "Died Ep. 49",
      url: "http://gameofthrones.wikia.com/wiki/Shireen_Baratheon",
      style: "",
      img: "Baratheon.jpg",
      symbols: [],
      id: 58,
    },
    {
      name: "Karsi",
      sub: "Died Ep. 48",
      url: "http://gameofthrones.wikia.com/wiki/Karsi",
      style: "",
      img: "",
      symbols: [],
      id: 57,
    },
    {
      name: "Rattleshirt",
      sub: "Died Ep. 48",
      url: "http://gameofthrones.wikia.com/wiki/Lord_of_Bones",
      style: "",
      img: "",
      symbols: [],
      id: 56,
    },
    {
      name: "Aemon Targaryen",
      sub: "Died Ep. 47",
      url: "http://gameofthrones.wikia.com/wiki/Aemon",
      style: "",
      img: "Targaryen.jpg",
      symbols: ["crow"],
      id: 55,
    },
    {
      name: "Barristan Selmy",
      sub: "Died Ep. 44",
      url: "http://gameofthrones.wikia.com/wiki/Barristan_Selmy",
      style: "",
      img: "",
      symbols: [],
      id: 54,
    },
    {
      name: "Janos Slynt",
      sub: "Died Ep. 43",
      url: "http://gameofthrones.wikia.com/wiki/Janos_Slynt",
      style: "",
      img: "",
      symbols: ["crow"],
      id: 53,
    },
    {
      name: "Mossador",
      sub: "Died Ep. 42",
      url: "http://gameofthrones.wikia.com/wiki/Mossador",
      style: "",
      img: "",
      symbols: [],
      id: 52,
    },
    {
      name: "Mance Rayder",
      sub: "Died Ep. 41",
      url: "http://gameofthrones.wikia.com/wiki/Mance_Rayder",
      style: "",
      img: "",
      symbols: [],
      id: 51,
    },
    {
      name: "Tywin Lannister",
      sub: "Died Ep. 40",
      url: "http://gameofthrones.wikia.com/wiki/Tywin_Lannister",
      style: "",
      img: "Lannister.jpg",
      symbols: [],
      id: 49,
    },
    {
      name: "Jojen Reed",
      sub: "Died Ep. 40",
      url: "http://gameofthrones.wikia.com/wiki/Jojen_Reed",
      style: "",
      img: "",
      symbols: [],
      id: 50,
    },
    {
      name: "Shae",
      sub: "Died Ep. 40",
      url: "http://gameofthrones.wikia.com/wiki/Shae",
      style: "",
      img: "",
      symbols: [],
      id: 48,
    },
    {
      name: "The Hound",
      sub: "Died Ep. 40",
      url: "http://gameofthrones.wikia.com/wiki/Sandor_Clegane",
      style: "",
      img: "",
      symbols: ["hand"],
      id: 66,
    },
    {
      name: "Ygritte",
      sub: "Died Ep. 39",
      url: "http://gameofthrones.wikia.com/wiki/Ygritte",
      style: "",
      img: "",
      symbols: [],
      id: 44,
    },
    {
      name: "Styr",
      sub: "Died Ep. 39",
      url: "http://gameofthrones.wikia.com/wiki/Styr",
      style: "",
      img: "",
      symbols: [],
      id: 47,
    },
    {
      name: "Pyp",
      sub: "Died Ep. 39",
      url: "http://gameofthrones.wikia.com/wiki/Pypar",
      style: "",
      img: "",
      symbols: ["crow"],
      id: 46,
    },
    {
      name: "Grenn",
      sub: "Died Ep. 39",
      url: "http://gameofthrones.wikia.com/wiki/Grenn",
      style: "",
      img: "",
      symbols: ["crow"],
      id: 45,
    },
    {
      name: "Oberyn Martell",
      sub: "Died Ep. 38",
      url: "http://gameofthrones.wikia.com/wiki/Oberyn_Martell",
      style: "",
      img: "Martell.jpg",
      symbols: [],
      id: 43,
    },
    {
      name: "Lysa Arryn",
      sub: "Died Ep. 37",
      url: "http://gameofthrones.wikia.com/wiki/Lysa_Arryn",
      style: "",
      img: "Arryn.jpg",
      symbols: [],
      id: 42,
    },
    {
      name: "Rorge",
      sub: "Died Ep. 37",
      url: "http://gameofthrones.wikia.com/wiki/Rorge",
      style: "",
      img: "",
      symbols: [],
      id: 41,
    },
    {
      name: "Biter",
      sub: "Died Ep. 37",
      url: "http://gameofthrones.wikia.com/wiki/Biter",
      style: "",
      img: "",
      symbols: [],
      id: 40,
    },
    {
      name: "Locke",
      sub: "Died Ep. 35",
      url: "http://gameofthrones.wikia.com/wiki/Locke",
      style: "",
      img: "",
      symbols: [],
      id: 37,
    },
    {
      name: "Karl Tanner",
      sub: "Died Ep. 35",
      url: "http://gameofthrones.wikia.com/wiki/Karl_Tanner",
      style: "",
      img: "",
      symbols: ["crow"],
      id: 39,
    },
    {
      name: "Rast",
      sub: "Died Ep. 35",
      url: "http://gameofthrones.wikia.com/wiki/Rast",
      style: "",
      img: "",
      symbols: ["crow"],
      id: 38,
    },
    {
      name: "Dontos Hollard",
      sub: "Died Ep. 33",
      url: "http://gameofthrones.wikia.com/wiki/Dontos_Hollard",
      style: "",
      img: "",
      symbols: [],
      id: 36,
    },
    {
      name: "Joffrey Baratheon",
      sub: "Died Ep. 32",
      url: "http://gameofthrones.wikia.com/wiki/Joffrey_Baratheon",
      style: "",
      img: "Baratheon.jpg",
      symbols: [],
      id: 32,
    },
    {
      name: "Polliver",
      sub: "Died Ep. 31",
      url: "http://gameofthrones.wikia.com/wiki/Polliver",
      style: "",
      img: "",
      symbols: [],
      id: 31,
    },
    {
      name: "Catelyn Stark",
      sub: "Died Ep. 29",
      url: "http://gameofthrones.wikia.com/wiki/Catelyn_Stark",
      style: "",
      img: "Stark.jpg",
      symbols: [],
      id: 6,
    },
    {
      name: "Grey Wind",
      sub: "Died Ep. 29",
      url: "http://gameofthrones.wikia.com/wiki/Grey_Wind",
      style: "",
      img: "Stark.jpg",
      symbols: [],
      id: 33,
    },
    {
      name: "Talisa Stark",
      sub: "Died Ep. 29",
      url: "http://gameofthrones.wikia.com/wiki/Talisa_Stark",
      style: "",
      img: "Stark.jpg",
      symbols: [],
      id: 7,
    },
    {
      name: "Robb Stark",
      sub: "Died Ep. 29",
      url: "http://gameofthrones.wikia.com/wiki/Robb_Stark",
      style: "",
      img: "Stark.jpg",
      symbols: [],
      id: 1,
    },
    {
      name: "Orell",
      sub: "Died Ep. 29",
      url: "http://gameofthrones.wikia.com/wiki/Orell",
      style: "",
      img: "",
      symbols: [],
      id: 28,
    },
    {
      name: "Ros",
      sub: "Died Ep. 26",
      url: "http://gameofthrones.wikia.com/wiki/Ros",
      style: "",
      img: "",
      symbols: [],
      id: 9,
    },
    {
      name: "Rickard Karstark",
      sub: "Died Ep. 25",
      url: "http://gameofthrones.wikia.com/wiki/Rickard_Karstark",
      style: "",
      img: "",
      symbols: [],
      id: 21,
    },
    {
      name: "Jeor Mormont",
      sub: "Died Ep. 24",
      url: "http://gameofthrones.wikia.com/wiki/Jeor_Mormont",
      style: "",
      img: "",
      symbols: ["crow"],
      id: 11,
    },
    {
      name: "Craster",
      sub: "Died Ep. 24",
      url: "http://gameofthrones.wikia.com/wiki/Craster",
      style: "",
      img: "",
      symbols: [],
      id: 16,
    },
    {
      name: "Hoster Tully",
      sub: "Died Ep. 23",
      url: "http://gameofthrones.wikia.com/wiki/Hoster_Tully",
      style: "",
      img: "Tully.jpg",
      symbols: [],
      id: 18,
    },
    {
      name: "Qhorin Halfhand",
      sub: "Died Ep. 20",
      url: "http://gameofthrones.wikia.com/wiki/Qhorin",
      style: "",
      img: "",
      symbols: ["crow"],
      id: 17,
    },
    {
      name: "Doreah",
      sub: "Died Ep. 20",
      url: "http://gameofthrones.wikia.com/wiki/Doreah",
      style: "",
      img: "",
      symbols: [],
      id: 13,
    },
    {
      name: "Pyat Pree",
      sub: "Died Ep. 20",
      url: "http://gameofthrones.wikia.com/wiki/Pyat_Pree",
      style: "",
      img: "",
      symbols: [],
      id: 22,
    },
    {
      name: "Maester Luwin",
      sub: "Died Ep. 20",
      url: "http://gameofthrones.wikia.com/wiki/Luwin",
      style: "",
      img: "",
      symbols: [],
      id: 29,
    },
    {
      name: "Xaro Xhoan Daxos",
      sub: "Died Ep. 20",
      url: "http://gameofthrones.wikia.com/wiki/Xaro_Xhoan_Daxos",
      style: "",
      img: "",
      symbols: [],
      id: 19,
    },
    {
      name: "Rodrik Cassel",
      sub: "Died Ep. 16",
      url: "http://gameofthrones.wikia.com/wiki/Rodrik_Cassel",
      style: "",
      img: "",
      symbols: [],
      id: 23,
    },
    {
      name: "Irri",
      sub: "Died Ep. 16",
      url: "http://gameofthrones.wikia.com/wiki/Irri",
      style: "",
      img: "",
      symbols: [],
      id: 24,
    },
    {
      name: "Amory Lorch",
      sub: "Died Ep. 16",
      url: "http://gameofthrones.wikia.com/wiki/Amory_Lorch",
      style: "",
      img: "",
      symbols: [],
      id: 20,
    },
    {
      name: "Renly Baratheon",
      sub: "Died Ep. 15",
      url: "http://gameofthrones.wikia.com/wiki/Renly_Baratheon",
      style: "",
      img: "Baratheon.jpg",
      symbols: [],
      id: 3,
    },
    {
      name: "The Tickler",
      sub: "Died Ep. 15",
      url: "http://gameofthrones.wikia.com/wiki/The_Tickler",
      style: "",
      img: "",
      symbols: [],
      id: 25,
    },
    {
      name: "Yoren",
      sub: "Died Ep. 13",
      url: "http://gameofthrones.wikia.com/wiki/Yoren",
      style: "",
      img: "",
      symbols: ["crow"],
      id: 15,
    },
    {
      name: "Lommy",
      sub: "Died Ep. 13",
      url: "http://gameofthrones.wikia.com/wiki/Lommy",
      style: "",
      img: "",
      symbols: ["crow"],
      id: 12,
    },
    {
      name: "Rakharo",
      sub: "Died Ep. 12",
      url: "http://gameofthrones.wikia.com/wiki/Rakharo",
      style: "",
      img: "",
      symbols: [],
      id: 27,
    },
    {
      name: "Septa Mordane",
      sub: "Died Ep. 10",
      url: "http://gameofthrones.wikia.com/wiki/Mordane",
      style: "",
      img: "",
      symbols: [],
      id: 35,
    },
    {
      name: "Mirri Maz Duur",
      sub: "Died Ep. 10",
      url: "http://gameofthrones.wikia.com/wiki/Mirri_Maz_Duur",
      style: "",
      img: "",
      symbols: [],
      id: 14,
    },
    {
      name: "Khal Drogo",
      sub: "Died Ep. 10",
      url: "http://gameofthrones.wikia.com/wiki/Drogo",
      style: "",
      img: "",
      symbols: [],
      id: 4,
    },
    {
      name: "Ned Stark",
      sub: "Died Ep. 9",
      url: "http://gameofthrones.wikia.com/wiki/Eddard_Stark",
      style: "",
      img: "Stark.jpg",
      symbols: [],
      id: 2,
    },
    {
      name: "Syrio Forel",
      sub: "Died Ep. 8",
      url: "http://gameofthrones.wikia.com/wiki/Syrio_Forel",
      style: "",
      img: "",
      symbols: [],
      id: 67,
    },
    {
      name: "Robert Baratheon",
      sub: "Died Ep. 7",
      url: "http://gameofthrones.wikia.com/wiki/Robert_Baratheon",
      style: "",
      img: "Baratheon.jpg",
      symbols: [],
      id: 5,
    },
    {
      name: "Viserys Targaryen",
      sub: "Died Ep. 6",
      url: "http://gameofthrones.wikia.com/wiki/Viserys_Targaryen",
      style: "",
      img: "Targaryen.jpg",
      symbols: [],
      id: 8,
    },
    {
      name: "Jory Cassel",
      sub: "Died Ep. 5",
      url: "http://gameofthrones.wikia.com/wiki/Jory_Cassel",
      style: "",
      img: "",
      symbols: [],
      id: 26,
    },
    {
      name: "Lady",
      sub: "Died Ep. 2",
      url: "http://gameofthrones.wikia.com/wiki/The_Kingsroad",
      style: "",
      img: "Stark.jpg",
      symbols: [],
      id: 34,
    },
    {
      name: "Mycah",
      sub: "Died Ep. 2",
      url: "http://gameofthrones.wikia.com/wiki/Mycah",
      style: "",
      img: "",
      symbols: [],
      id: 30,
    },
    {
      name: "Jon Arryn",
      sub: "Died Ep. 1",
      url: "http://gameofthrones.wikia.com/wiki/Jon_Arryn",
      style: "",
      img: "Arryn.jpg",
      symbols: [],
      id: 10,
    },
  ],
};
